### ISSUE TITLE
apartment control broken

### ISSUE THREAD

**Issue by TornadoVulkan** [lociii/homeassistant-config#16] opened 2019-09-03 12:02 UTC
See Screenshot. please fix. Thanks!

![Screenshot_2019-09-03-09-33-46-352_com android chrome](https://user-images.githubusercontent.com/45716363/64171678-81650700-ce53-11e9-91ab-52acd3670135.png)

**Comment by lociii** [comment] 2019-09-04 21:04
Since this repository is public:
This report was created by my wife. Please excuse her brusque wording.

This was caused by a flawed update of my own custom digitalSTROM component and will be addressed in the related repository

**Closed as completed by lociii** 2019-09-04 21:04 UTC
